# Site settings
title: Your awesome title
email: your-email@domain.com
description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque molestias pariatur modi vel beatae non fugit enim delectus dicta, dignissimos voluptatum harum sunt consequatur reprehenderit nostrum rem iusto deserunt optio!

# Posts
excerpt_separator: "<!--more-->"
# defaults:
#   -
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"

# Slim
slim:
  pretty: true

# Links
# baseurl: "/dynamo-ops"
baseurl: ""
permalink: /categories/:categories/:title/

# Build settings
markdown: kramdown

# Gulp & Bower
exclude: [
  gulpfile.js,
  package.json,
  node_modules,
  bower.json,
  bower_components,
  Gemfile,
  Gemfile.lock,
  wercker.yml
]
