# Site settings
title: Your awesome title
email: your-email@domain.com
description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque molestias pariatur modi vel beatae non fugit enim delectus dicta, dignissimos voluptatum harum sunt consequatur reprehenderit nostrum rem iusto deserunt optio!

# Posts
excerpt_separator: "<!--more-->"

# Slim
slim:
  pretty: true

# Links
baseurl: ""
permalink: /categories/:categories/:title/

# Build settings
markdown: kramdown
highlighter: true

# Gulp & Bower
exclude: [
  gulpfile.js,
  package.json,
  node_modules,
  Gemfile,
  Gemfile.lock,
  wercker.yml
]

#
category_meta_description_prefix: ''
category_description_prefix: ''
